version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: taskify-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: taskify
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - taskify-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: taskify-server
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 4000
      MONGO_URL: mongodb://admin:password123@mongodb:27017/taskify?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - taskify-network
    command: npm run dev

  mongo-express:
    image: mongo-express:1.0.0
    container_name: taskify-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - taskify-network

volumes:
  mongodb_data:
    driver: local

networks:
  taskify-network:
    driver: bridge
