version: "3.8"
services:
  backend:
    image: jaydeep2003/testify:latest
    container_name: backend
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
