version: "3.8"
services:
  backend:
    build: ./server
    container_name: backend
    env_file:
      - ./server/.env
    ports:           
s      - "4000:4000"

  frontend:
    build: ./client
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf  
