version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - "80"
    restart: unless-stopped

  backend:
    image: jaydeep2003/testify:latest
    container_name: backend
    expose:
      - "4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped